# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filip/workspace/tests-generation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filip/workspace/tests-generation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filip/workspace/tests-generation/CMakeFiles /home/filip/workspace/tests-generation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filip/workspace/tests-generation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_main.dir/build.make tests/CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test-unit-dist

# Build rule for target.
test-unit-dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-dist
.PHONY : test-unit-dist

# fast build rule for target.
test-unit-dist/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-dist.dir/build.make tests/CMakeFiles/test-unit-dist.dir/build
.PHONY : test-unit-dist/fast

#=============================================================================
# Target rules for targets named test-unit-dump

# Build rule for target.
test-unit-dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-dump
.PHONY : test-unit-dump

# fast build rule for target.
test-unit-dump/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-dump.dir/build.make tests/CMakeFiles/test-unit-dump.dir/build
.PHONY : test-unit-dump/fast

#=============================================================================
# Target rules for targets named test-unit-graph

# Build rule for target.
test-unit-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-graph
.PHONY : test-unit-graph

# fast build rule for target.
test-unit-graph/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-graph.dir/build.make tests/CMakeFiles/test-unit-graph.dir/build
.PHONY : test-unit-graph/fast

#=============================================================================
# Target rules for targets named test-unit-manager

# Build rule for target.
test-unit-manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-manager
.PHONY : test-unit-manager

# fast build rule for target.
test-unit-manager/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-manager.dir/build.make tests/CMakeFiles/test-unit-manager.dir/build
.PHONY : test-unit-manager/fast

#=============================================================================
# Target rules for targets named test-unit-output

# Build rule for target.
test-unit-output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-output
.PHONY : test-unit-output

# fast build rule for target.
test-unit-output/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-output.dir/build.make tests/CMakeFiles/test-unit-output.dir/build
.PHONY : test-unit-output/fast

#=============================================================================
# Target rules for targets named test-unit-sequence

# Build rule for target.
test-unit-sequence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-sequence
.PHONY : test-unit-sequence

# fast build rule for target.
test-unit-sequence/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-sequence.dir/build.make tests/CMakeFiles/test-unit-sequence.dir/build
.PHONY : test-unit-sequence/fast

#=============================================================================
# Target rules for targets named test-unit-single_test

# Build rule for target.
test-unit-single_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-single_test
.PHONY : test-unit-single_test

# fast build rule for target.
test-unit-single_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-single_test.dir/build.make tests/CMakeFiles/test-unit-single_test.dir/build
.PHONY : test-unit-single_test/fast

#=============================================================================
# Target rules for targets named test-unit-testing

# Build rule for target.
test-unit-testing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unit-testing
.PHONY : test-unit-testing

# fast build rule for target.
test-unit-testing/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-unit-testing.dir/build.make tests/CMakeFiles/test-unit-testing.dir/build
.PHONY : test-unit-testing/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test-unit-dist"
	@echo "... test-unit-dump"
	@echo "... test-unit-graph"
	@echo "... test-unit-manager"
	@echo "... test-unit-output"
	@echo "... test-unit-sequence"
	@echo "... test-unit-single_test"
	@echo "... test-unit-testing"
	@echo "... test_main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

