name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo hello world
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and test
        run: mkdir build && cd build && cmake .. && make && make test
